import test from "node:test";
import assert from "node:assert/strict";
import {knight,content} from "./foundry-stub.mjs";
import {prepareKnight} from "../module/rules.mjs";
import {actionView,actionPlan,actionHash,stampCombatRound,techniqueActionPlan} from "../module/action-rules.mjs";
import {combatActionState,submitCombatAction,enqueueActionRequest,executeActionRequest,recoverAction,reviewAction,adjustActions,toggleActionControl,resumeActionRequests} from "../module/actions.mjs";
import {activationState,executeTechniqueRequest,recoverTechniqueOperation} from "../module/technique-activation.mjs";
import {techniqueParameters,cosmoPayment} from "../module/technique-rules.mjs";
import {assertNoTechniqueInterruption} from "../module/master-queue.mjs";
import {attackTarget,defendAttack} from "../module/combat.mjs";
const ID="gods-battle-ss",clone=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
function patch(object,data){for(const[path,value]of Object.entries(data)){const keys=path.split(".");let at=object;for(const key of keys.slice(0,-1))at=at[key]??={};if(keys.at(-1).startsWith("-="))delete at[keys.at(-1).slice(2)];else at[keys.at(-1)]=clone(value);}}
function runtime(){
 const gm={id:"gm",isGM:true,active:true},owner={id:"owner"},other={id:"other"},outsider={id:"outsider"},users=new Map([gm,owner,other,outsider].map(u=>[u.id,u])),messages=new Map(),actors=new Map(),renders=[],updates=[],stats={rolls:0,paid:0,published:0},control={beforeRoll:null,saveFail:null,publishFail:false,answer:null};
 globalThis.game={user:owner,users:{activeGM:gm,get:id=>users.get(id)},messages:{get:id=>messages.get(id),get contents(){return [...messages.values()];}},settings:{get:()=>"publicroll"},combats:{contents:[]}};
 globalThis.ui={notifications:{error:()=>{},warn:()=>{},info:()=>{}}};
 foundry.utils={randomID:()=>`epoch${++control.ids}`};control.ids=0;
 foundry.applications.api.DialogV2={confirm:async()=>true,wait:async()=>control.answer};
 foundry.applications.handlebars={renderTemplate:async(path,context)=>{renders.push({path,context});return "<p>Resultado</p>";}};
 foundry.dice={terms:{OperatorTerm:class{constructor(data){Object.assign(this,data);}}}};
 globalThis.Roll=class{constructor(formula){this.formula=formula;}async evaluate(){if(this.formula.includes("d10")){stats.rolls++;if(control.beforeRoll)await control.beforeRoll();this.dice=[{results:[{result:8}]}];this.terms=[{number:8}];}else this.terms=[{number:Number(this.formula)}];return this;}static fromTerms(terms){return {total:terms[0].number+(terms[1].operator==="+"?1:-1)*terms[2].number,toJSON:()=>({total:terms[0].number+(terms[1].operator==="+"?1:-1)*terms[2].number})};}static fromData(data){return{...data,toJSON:()=>data};}};
 const doc=data=>({...data,async update(change){if(change.rolls&&control.publishFail)throw Error("Publicação interrompida");patch(this,change);if(change.rolls)stats.published++;return this;}});
 globalThis.ChatMessage={getSpeaker:({actor})=>({actor:actor.id}),applyRollMode:(data,mode)=>{data.whisper=mode==="publicroll"?[]:mode==="selfroll"?[game.user.id]:[gm.id];data.blind=mode==="blindroll";},create:async data=>{const m=doc({...clone(data),id:`request${messages.size+1}`,author:game.user});messages.set(m.id,m);return m;}};
 const makeActor=(id)=>{const system=knight();system.profile.level=11;system.combat.attackBonus=-8;system.combat.defenseBonus=-8;system.skills.asterism.value=2;system.fighting.punch=2;system.fighting.defense=2;system.resources.cosmo.value=10;prepareKnight(system);const actor={uuid:`Actor.${id}`,id,name:id,type:"knight",system,flags:{},isOwner:true,testUserPermission:u=>u?.isGM||[owner.id,other.id].includes(u?.id),async update(change){updates.push(change);const paid=Object.hasOwn(change,`flags.${ID}.actionUsage`);if(paid&&control.saveFail==="before")throw Error("Gravação interrompida");patch(this,change);if(paid)stats.paid++;if(paid&&control.saveFail==="after")throw Error("Resposta perdida");return this;}};actors.set(actor.uuid,actor);const item={id:"tech",uuid:`Actor.${id}.Item.tech`,name:"Técnica de teste",type:"technique",parent:actor,isOwner:true,system:content(),flags:{}};actor.items={contents:[item],get:id=>id===item.id?item:null};return actor;};
 const actor=makeActor("hero"),target=makeActor("target"),combat=doc({uuid:"Combat.battle",round:1,turn:0,started:true,flags:{[ID]:{actionControl:{enabled:true,epoch:"epoch0"}}},combatants:{contents:[{id:"heroCombatant",actor},{id:"targetCombatant",actor:target}]}});game.combat=combat;game.combats.contents=[combat];globalThis.fromUuid=async uuid=>actors.get(uuid);
 const attack=(amount=2)=>({kind:"attack",fighting:"punch",targetUuid:target.uuid,amount,bonus:0});
 const request=(options=attack(),id=`action${messages.size}`,who=actor,user=owner)=>{const m=doc({id,author:user,flags:{[ID]:{actionRequest:{actorUuid:who.uuid,baseline:combatActionState(who),options,rollMode:"publicroll"}}}});messages.set(id,m);return m;};
 const techRequest=(pool="attack",id="techRequest")=>{const item=actor.items.get("tech"),options={extra:0,elevate:0,condense:0,bonus:0,advantage:0,useExtra:true,allowOverload:false,actionPool:pool},p=techniqueParameters(actor.system,item.system,options);const m=doc({id,author:owner,flags:{[ID]:{techniqueRequest:{actorUuid:actor.uuid,itemId:item.id,itemUuid:item.uuid,baseline:activationState(actor,item),options,expectedPayment:cosmoPayment(actor.system,p.cost,options),targetUuid:target.uuid,rollMode:"publicroll"}}}});messages.set(id,m);return m;};
 const execute=async m=>{game.user=gm;return executeActionRequest(m,m.author.id);};
 const round=(number)=>{const changes={round:number};stampCombatRound(combat,changes);patch(combat,changes);};
 return{gm,owner,other,outsider,actor,target,combat,actors,messages,control,stats,renders,updates,attack,request,execute,round,techRequest};
}
test("controle é por encontro iniciado; fora dele preserva reservas e CE",()=>{const r=runtime();assert.equal(actionView(r.actor).enabled,true);r.combat.started=false;assert.equal(actionView(r.actor).enabled,false);assert.deepEqual(techniqueActionPlan(r.actor,{},"id").updates,{});r.combat.started=true;r.combat.flags[ID].actionControl.enabled=false;assert.equal(actionView(r.actor).enabled,false);assert.equal(r.actor.system.resources.cosmo.value,10);});
test("rodada repõe, mudança de vez não; retroceder/repetir rodada não restaura histórico antigo",()=>{const r=runtime();patch(r.actor,actionPlan(r.actor,"attack",2,{operationId:"first"}).updates);assert.equal(actionView(r.actor).remaining.attack,1);r.combat.turn=1;assert.equal(actionView(r.actor).remaining.attack,1);r.round(2);assert.equal(actionView(r.actor).remaining.attack,3);patch(r.actor,actionPlan(r.actor,"attack",1,{operationId:"second"}).updates);r.round(1);assert.equal(actionView(r.actor).remaining.attack,3);assert.equal(r.actor.flags[ID].actionUsage.context.round,2);r.combat.started=false;assert.equal(actionView(r.actor).enabled,false);});
test("máximos alterados conservam gasto; fichas duplicadas e tokens sintéticos não herdam consumo",()=>{const r=runtime();patch(r.actor,actionPlan(r.actor,"attack",2,{operationId:"one"}).updates);r.actor.system.combat.attack=5;assert.equal(actionView(r.actor).remaining.attack,3);const copied={...r.actor,uuid:"Scene.map.Token.copy.Actor.hero"};r.combat.combatants.contents.push({id:"copy",actor:copied});assert.equal(actionView(copied).remaining.attack,5);r.actor.system.combat.attack=1;assert.equal(actionView(r.actor).remaining.attack,0);});
test("múltiplos combatentes vinculados e encontros simultâneos exigem resolução explícita",()=>{const r=runtime();r.combat.combatants.contents.push({id:"double",actor:r.actor});assert.throws(()=>actionView(r.actor),/mais de um combatente/);r.combat.combatants.contents.pop();game.combats.contents.push({...r.combat,uuid:"Combat.other"});assert.throws(()=>actionView(r.actor),/mais de um combate/);});
test("ataque usa ações escolhidas na fórmula e paga uma vez no mestre",async()=>{const r=runtime(),m=r.request();await r.execute(m);assert.equal(r.renders[0].context.modifier,2+r.actor.system.combat.levelModifier);assert.equal(actionView(r.actor).remaining.attack,1);assert.equal(actionView(r.actor).remaining.defense,3);assert.equal(r.actor.system.resources.cosmo.value,10);assert.equal(r.stats.rolls,1);await r.execute(m);assert.equal(r.stats.paid,1);assert.equal(r.stats.rolls,1);assert.equal(m.flags[ID].actionRequest,undefined);assert.equal(m.flags[ID].fight.targetUuid,r.target.uuid);assert.equal(r.actor.flags[ID].actionOperations[m.id].card,undefined);});
test("duas solicitações concorrentes sobre mesma reserva processam uma",async()=>{const r=runtime(),a=r.request(r.attack(),"one"),b=r.request(r.attack(),"two",r.actor,r.other);game.user=r.gm;await Promise.all([enqueueActionRequest(a,{},r.owner.id),enqueueActionRequest(b,{},r.other.id)]);assert.equal(r.stats.paid,1);assert.equal(b.flags[ID].actionResponse.status,"failed");assert.equal(r.stats.rolls,1);});
test("defesa fora da vez usa reserva própria; replay do mesmo ataque não consome outra defesa",async()=>{const r=runtime(),attack=r.request();await r.execute(attack);r.combat.turn=0;const options={kind:"defend",rootId:attack.id,fightHash:actionHash(attack.flags[ID].fight),amount:1,bonus:0},d=r.request(options,"defend",r.target);await r.execute(d);assert.equal(actionView(r.target).remaining.defense,2);assert.equal(d.flags[ID].resolvedDamage.rootMessageId,attack.id);const replay=r.request(options,"replay",r.target);await r.execute(replay);assert.equal(replay.flags[ID].actionResponse.status,"failed");assert.equal(r.stats.rolls,2);});
test("defesa recusa cartão privado/cego, outro alvo e ataque de rodada anterior",async()=>{for(const kind of ["private","blind","target","round"]){const r=runtime(),attack=r.request();await r.execute(attack);if(kind==="private")attack.whisper=[r.gm.id];if(kind==="blind")attack.blind=true;if(kind==="target")attack.flags[ID].fight.targetUuid=r.actor.uuid;if(kind==="round")r.round(2);const d=r.request({kind:"defend",rootId:attack.id,fightHash:actionHash(attack.flags[ID].fight),amount:1,bonus:0},"def",r.target);await r.execute(d);assert.equal(d.flags[ID].actionResponse.status,"failed",kind);assert.equal(actionView(r.target).remaining.defense,3);}});
test("autoria, proprietário, GM e quantidade inválida não gastam ações",async()=>{for(const kind of ["owner","author","gm","zero","excess"]){const r=runtime(),m=r.request(r.attack(kind==="zero"?0:kind==="excess"?4:2));game.user=r.gm;if(kind==="owner")r.actor.testUserPermission=()=>false;if(kind==="gm")game.user=r.owner;await executeActionRequest(m,kind==="author"?r.outsider.id:r.owner.id);assert.equal(r.stats.paid,0,kind);assert.equal(r.stats.rolls,0,kind);}});
test("público/GM/cego/self preservam autoria e modos sem dados no journal do Actor",async()=>{for(const mode of ["publicroll","gmroll","blindroll","selfroll"]){const r=runtime(),m=r.request();m.flags[ID].actionRequest.rollMode=mode;await r.execute(m);assert.equal(m.author.id,r.owner.id);assert.equal(m.blind,mode==="blindroll");assert.deepEqual(m.whisper,mode==="publicroll"?[]:mode==="selfroll"?[r.owner.id]:[r.gm.id]);assert.equal(r.actor.flags[ID].actionOperations[m.id].rolls,undefined);}});
test("técnica consome reserva inteira junto com CE numa gravação; outra reserva permanece",async()=>{const r=runtime(),m=r.techRequest();game.user=r.gm;await executeTechniqueRequest(m,r.owner.id);assert.equal(actionView(r.actor).remaining.attack,0);assert.equal(actionView(r.actor).remaining.defense,3);assert.equal(r.actor.system.resources.cosmo.value,8);const atomic=r.updates.find(u=>Object.hasOwn(u,"system.combat.asterismPenalty"));assert.equal(atomic[`flags.${ID}.actionUsage`].spent.attack,3);assert.equal(atomic["system.resources.cosmo.value"],8);assert.equal(r.stats.rolls,1);});
test("técnica recusa reserva parcialmente gasta antes de rolar/gastar CE; defesa intacta é alternativa",async()=>{const r=runtime();patch(r.actor,actionPlan(r.actor,"attack",1,{operationId:"earlier"}).updates);const bad=r.techRequest();game.user=r.gm;await executeTechniqueRequest(bad,r.owner.id);assert.equal(r.stats.rolls,0);assert.equal(r.actor.system.resources.cosmo.value,10);const good=r.techRequest("defense","good");await executeTechniqueRequest(good,r.owner.id);assert.equal(actionView(r.actor).remaining.attack,2);assert.equal(actionView(r.actor).remaining.defense,0);assert.equal(r.actor.system.resources.cosmo.value,8);});
test("movimento/reação são registros de um uso, não acumulam e não cobram CE",async()=>{for(const pool of ["movement","reaction"]){const r=runtime(),m=r.request({kind:"consume",pool,amount:1,reason:"Uso conferido"});await r.execute(m);assert.equal(actionView(r.actor).remaining[pool],0);assert.equal(r.stats.rolls,0);assert.equal(r.actor.system.resources.cosmo.value,10);const next=r.request({kind:"consume",pool,amount:1,reason:"Repetir"});await r.execute(next);assert.equal(next.flags[ID].actionResponse.status,"failed");r.round(2);assert.equal(actionView(r.actor).remaining[pool],1);}});
test("mudança de rodada/alvo/permissão durante rolagem interrompe sem gasto; recuperação não rola",async()=>{for(const kind of ["round","target","owner"]){const r=runtime(),m=r.request();r.control.beforeRoll=async()=>{if(kind==="round")r.round(2);if(kind==="target")r.actors.delete(r.target.uuid);if(kind==="owner")r.actor.testUserPermission=()=>false;};await r.execute(m);assert.equal(r.stats.paid,0);assert.equal(m.flags[ID].actionResponse.status,"interrupted");assert.throws(()=>assertNoTechniqueInterruption(r.actor),/ações interrompido/);await recoverAction(r.actor,m.id);assert.equal(r.actor.flags[ID].actionOperations[m.id].status,"failed");assert.equal(r.stats.rolls,1);}});
test("troca de mestre interrompe, retomada não repete rolagem",async()=>{const r=runtime(),m=r.request();r.control.beforeRoll=async()=>{game.users.activeGM={id:"newGM",isGM:true,active:true};};await r.execute(m);assert.equal(r.stats.paid,0);game.users.activeGM=r.gm;await resumeActionRequests();assert.equal(r.stats.rolls,1);assert.equal(m.flags[ID].actionResponse.status,"interrupted");});
test("falha de gravação antes/depois distingue sem gasto/pago e conserva resultado",async()=>{for(const when of ["before","after"]){const r=runtime(),m=r.request();r.control.saveFail=when;await r.execute(m);r.control.saveFail=null;await recoverAction(r.actor,m.id);assert.equal(r.stats.rolls,1);assert.equal(actionView(r.actor).remaining.attack,when==="before"?3:1);assert.equal(m.flags[ID].actionResponse.status,when==="before"?"failed":"published");}});
test("falha de publicação recupera mesmo cartão sem alterar ações da próxima rodada",async()=>{const r=runtime(),m=r.request();r.control.publishFail=true;await r.execute(m);assert.equal(r.stats.paid,1);r.control.publishFail=false;r.round(2);patch(r.actor,actionPlan(r.actor,"defense",1,{operationId:"later"}).updates);const current=clone(r.actor.flags[ID].actionUsage);await recoverAction(r.actor,m.id);assert.deepEqual(r.actor.flags[ID].actionUsage,current);assert.equal(r.stats.rolls,1);assert.equal(r.stats.paid,1);assert.equal(m.flags[ID].actionResponse.status,"published");});
test("journal preparado reconhece estado posterior completo; cartão adulterado exige revisão",async()=>{const r=runtime(),m=r.request();r.control.saveFail="before";await r.execute(m);const record=r.actor.flags[ID].actionOperations[m.id];r.control.saveFail=null;patch(r.actor,{[`flags.${ID}.actionUsage`]:record.after});await recoverAction(r.actor,m.id);assert.equal(m.flags[ID].actionResponse.status,"published");assert.equal(r.stats.rolls,1);const s=runtime(),n=s.request();s.control.publishFail=true;await s.execute(n);s.control.publishFail=false;n.flags[ID].actionPrepared.card.content="Alterado";await assert.rejects(()=>recoverAction(s.actor,n.id),/alterado/);assert.equal(s.stats.rolls,1);});
test("ajuste do mestre exige motivo, conserva recursos e registra antes/depois",async()=>{const r=runtime();game.user=r.gm;r.control.answer={values:{attack:1,defense:3,movement:0,reaction:1},reason:"Manobra conferida"};await adjustActions(r.actor);assert.equal(actionView(r.actor).remaining.attack,1);assert.equal(actionView(r.actor).remaining.movement,0);assert.equal(r.actor.system.resources.cosmo.value,10);assert.equal(Object.values(r.actor.flags[ID].actionAdjustments)[0].reason,"Manobra conferida");r.control.answer={values:{attack:99,defense:3,movement:0,reaction:1},reason:""};await assert.rejects(()=>adjustActions(r.actor),/Justifique/);});
test("revisão de cópia interrompida não toca original/cartão nem restaura reservas",async()=>{const r=runtime(),m=r.request();r.control.saveFail="before";await r.execute(m);r.control.saveFail=null;const copied={...r.actor,uuid:"Actor.copy",flags:clone(r.actor.flags)};await assert.rejects(()=>recoverAction(copied,m.id),/outra ficha/);r.control.answer={reason:"Cópia conferida",checked:true};await reviewAction(copied,m.id);assert.equal(copied.flags[ID].actionOperations[m.id].status,"reviewed");assert.equal(r.actor.flags[ID].actionOperations[m.id].status,"prepared");assert.ok(m.flags[ID].actionRequest);});
test("controle só muda pelo GM responsável após confirmação e não altera fichas",async()=>{const r=runtime();await assert.rejects(()=>toggleActionControl(),/mestre responsável/);game.user=r.gm;const before=clone(r.actor.system);await toggleActionControl();assert.equal(r.combat.flags[ID].actionControl.enabled,false);assert.deepEqual(r.actor.flags,{});assert.equal(r.actor.system.resources.cosmo.value,before.resources.cosmo.value);await toggleActionControl();assert.equal(actionView(r.actor).remaining.attack,3);});
test("envio privado não rola/gasta localmente; desativação e ausência de GM recusam envio",async()=>{const r=runtime(),m=await submitCombatAction(r.actor,r.attack());assert.deepEqual(m.whisper,[r.owner.id,r.gm.id]);assert.equal(r.stats.rolls,0);assert.equal(r.stats.paid,0);await assert.rejects(()=>submitCombatAction(r.actor,r.attack()),/aguardando/);r.messages.clear();game.users.activeGM=null;await assert.rejects(()=>submitCombatAction(r.actor,r.attack()),/mestre conectado/);});
test("técnica interrompida com mudança de rodada recupera sem consumir ações/CE",async()=>{const r=runtime(),m=r.techRequest();r.control.beforeRoll=async()=>r.round(2);game.user=r.gm;await executeTechniqueRequest(m,r.owner.id);assert.equal(r.actor.system.resources.cosmo.value,10);await recoverTechniqueOperation(r.actor,m.id);assert.equal(m.flags[ID].techniqueResponse.status,"failed");assert.equal(actionView(r.actor).remaining.attack,3);assert.equal(r.stats.rolls,1);});

test("Combate acima de cinco soma ações uma vez com automação avançada; ajustes e gastos são preservados",()=>{const r=runtime();r.actor.system.automation.enabled=true;r.actor.system.skills.combat.value=7;const before=r.actor.system.resources.cosmo.value;prepareKnight(r.actor.system);assert.equal(actionView(r.actor).maxima.attack,5);patch(r.actor,actionPlan(r.actor,"attack",2,{operationId:"one"}).updates);prepareKnight(r.actor.system);assert.equal(actionView(r.actor).remaining.attack,3);assert.equal(r.actor.system.combat.attackBonus,-8);assert.equal(r.actor.system.resources.cosmo.value,before);r.actor.system.automation.enabled=false;prepareKnight(r.actor.system);assert.equal(actionView(r.actor).maxima.attack,3);assert.equal(actionView(r.actor).remaining.attack,1);});
test("interface confirma quantidade, cancelamento conserva ações e defesa pelo cartão mantém vínculo",async()=>{const r=runtime();r.owner.targets=new Set([{actor:r.target}]);r.control.answer=null;await attackTarget(r.actor);assert.equal(r.messages.size,0);r.control.answer={kind:"punch",bonus:0,amount:2};const attack=await attackTarget(r.actor);assert.equal(r.stats.rolls,0);await r.execute(attack);attack.isContentVisible=true;game.user=r.owner;r.control.answer={bonus:0,amount:1};const defense=await defendAttack(attack);assert.equal(r.stats.rolls,1);await r.execute(defense);assert.equal(defense.flags[ID].resolvedDamage.actorUuid,r.target.uuid);assert.equal(actionView(r.target).remaining.defense,2);});
test("falha de Asterismo consome ações e CE, sem produzir ataque",async()=>{const r=runtime();r.actor.items.get("tech").system.cost=4;const m=r.techRequest();game.user=r.gm;await executeTechniqueRequest(m,r.owner.id);assert.equal(r.renders.at(-1).context.success,false);assert.equal(actionView(r.actor).remaining.attack,0);assert.equal(r.actor.system.resources.cosmo.value,6);assert.equal(m.flags[ID].attack,undefined);});
test("fila compartilhada entre técnica e ataque não usa a reserva anterior duas vezes",async()=>{const r=runtime(),tech=r.techRequest(),attack=r.request();game.user=r.gm;await executeTechniqueRequest(tech,r.owner.id);await enqueueActionRequest(attack,{},r.owner.id);assert.equal(r.stats.rolls,1);assert.equal(attack.flags[ID].actionResponse.status,"failed");assert.equal(actionView(r.actor).remaining.attack,0);assert.equal(r.actor.system.resources.cosmo.value,8);});
test("ataque original alterado durante defesa impede gasto",async()=>{const r=runtime(),attack=r.request();await r.execute(attack);const d=r.request({kind:"defend",rootId:attack.id,fightHash:actionHash(attack.flags[ID].fight),amount:1,bonus:0},"def",r.target);r.control.beforeRoll=async()=>{attack.flags[ID].fight.attack++;};await r.execute(d);assert.equal(actionView(r.target).remaining.defense,3);assert.equal(d.flags[ID].actionResponse.status,"interrupted");await recoverAction(r.target,d.id);assert.equal(r.stats.rolls,2);});
test("revisão divergente exige confirmação/motivo e preserva ajustes feitos após interrupção",async()=>{const r=runtime(),m=r.request();r.control.saveFail="before";await r.execute(m);r.control.saveFail=null;patch(r.actor,actionPlan(r.actor,"reaction",1,{operationId:"repair"}).updates);await assert.rejects(()=>recoverAction(r.actor,m.id),/alteradas/);r.control.answer={reason:"",checked:false};await assert.rejects(()=>reviewAction(r.actor,m.id),/Confirme/);const current=clone(r.actor.flags[ID].actionUsage);r.control.answer={reason:"Reparo conferido",checked:true};await reviewAction(r.actor,m.id);assert.deepEqual(r.actor.flags[ID].actionUsage,current);assert.equal(r.actor.flags[ID].actionOperations[m.id].status,"reviewed");assert.equal(r.stats.rolls,1);});
test("condições assistidas alteram ataque/defesa controlados sem reduzir reservas máximas",async()=>{
 const r=runtime();r.actor.flags[ID]={conditionEffects:{fatigue:{actorUuid:r.actor.uuid,status:"active",key:"tired",count:2,ruleVersion:1,reviewedManual:true},limb:{actorUuid:r.actor.uuid,status:"active",key:"incapacitated",count:1,ruleVersion:1,reviewedManual:true}}};prepareKnight(r.actor.system,r.actor.items.contents,"rank",{actorUuid:r.actor.uuid,flags:r.actor.flags});const maxima=actionView(r.actor).maxima;const m=r.request();await r.execute(m);assert.equal(r.renders[0].context.modifier,2+r.actor.system.combat.levelModifier-6);assert.deepEqual(actionView(r.actor).maxima,maxima);assert.match(r.renders[0].context.conditionSummary,/−1 dado/);
 r.target.flags[ID]={conditionEffects:{limb:{actorUuid:r.target.uuid,status:"active",key:"incapacitated",count:1,ruleVersion:1,reviewedManual:true}}};prepareKnight(r.target.system,r.target.items.contents,"rank",{actorUuid:r.target.uuid,flags:r.target.flags});const d=r.request({kind:"defend",rootId:m.id,fightHash:actionHash(m.flags[ID].fight),amount:1,bonus:0},"defender",r.target);await r.execute(d);assert.equal(r.renders.at(-1).context.modifier,1+r.target.system.combat.levelModifier-2);assert.equal(d.flags[ID].actionResponse.status,"published");
});
test("mudança de condição durante rolagem de ação não paga confirmação antiga",async()=>{
 const r=runtime(),m=r.request();r.control.beforeRoll=()=>{r.actor.flags[ID]??={};r.actor.flags[ID].conditionEffects={fatigue:{actorUuid:r.actor.uuid,status:"active",key:"tired",count:1,ruleVersion:1,reviewedManual:true}};prepareKnight(r.actor.system,r.actor.items.contents,"rank",{actorUuid:r.actor.uuid,flags:r.actor.flags});};await r.execute(m);assert.equal(r.stats.paid,0);assert.equal(actionView(r.actor).remaining.attack,3);assert.equal(m.flags[ID].actionResponse.status,"interrupted");
});
test("ataque/defesa fora do controle também aplicam condições sem gastar reservas",async()=>{
 const r=runtime();r.combat.flags[ID].actionControl.enabled=false;r.actor.flags[ID]={conditionEffects:{fatigue:{actorUuid:r.actor.uuid,status:"active",key:"tired",count:2,ruleVersion:1,reviewedManual:true}}};prepareKnight(r.actor.system,r.actor.items.contents,"rank",{actorUuid:r.actor.uuid,flags:r.actor.flags});game.user.targets=new Set([{actor:r.target}]);r.control.answer={kind:"punch",bonus:0};await attackTarget(r.actor);assert.equal(r.renders[0].context.modifier,r.actor.system.combat.attack+r.actor.system.combat.levelModifier-4);const attack=[...r.messages.values()].find(m=>m.flags[ID].fight);
 r.target.flags[ID]={conditionEffects:{limb:{actorUuid:r.target.uuid,status:"active",key:"incapacitated",count:1,ruleVersion:1,reviewedManual:true}}};prepareKnight(r.target.system,r.target.items.contents,"rank",{actorUuid:r.target.uuid,flags:r.target.flags});attack.isContentVisible=true;r.control.answer={bonus:0};await defendAttack(attack);assert.equal(r.renders.at(-1).context.modifier,r.target.system.combat.defense+r.target.system.combat.levelModifier-2);assert.equal(r.stats.paid,0);assert.equal(r.actor.system.resources.cosmo.value,10);
});
