import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {knight,content} from "./foundry-stub.mjs";
import {prepareKnight} from "../module/rules.mjs";
import {componentState,componentProfile,techniqueWithComponents,componentOptions,COMPONENT_RULES} from "../module/technique-components.mjs";
import {techniqueParameters,activationPreview} from "../module/technique-rules.mjs";
import {techniqueSetupUpdates} from "../module/technique-setup.mjs";
const ID="gods-battle-ss";
const entries=Object.entries(COMPONENT_RULES).map(([id,rule])=>({uuid:`Compendium.${ID}.componentes-tecnicas.Item.${id}`,key:rule.key,type:rule.kind==="space"?"increment":"bigbang",rank:rule.kind==="space"?3:1,name:rule.label,page:rule.page,detail:rule.kind==="terrain"?"Campo de gelo":""}));
function fixture(){const system=knight();system.resources.cosmo.value=20;prepareKnight(system);const item={type:"technique",name:"Técnica de exercício",system:{...content(),cost:5,costExtra:1},flags:{[ID]:{componentAutomation:true,techniqueConstructionId:"saved",techniqueConstructionHistory:{saved:{primary:{label:"Dano",uuid:"Compendium.gods-battle-ss.componentes-tecnicas.Item.13841831d802c5be"},components:structuredClone(entries)}}}}};return {system,item};}
test("quatro regras têm ID/chave/graduação conferidos contra catálogo; nomes não concedem efeitos",async()=>{const docs=[...JSON.parse(await readFile("data/catalog/bigbangs.json","utf8")),...JSON.parse(await readFile("data/catalog/increments.json","utf8"))];for(const[id,rule]of Object.entries(COMPONENT_RULES)){const doc=docs.find(d=>d._id===id);assert.ok(doc);assert.equal(doc.flags[ID].source.key,rule.key);}const {item}=fixture();item.flags[ID].techniqueConstructionHistory.saved.components[0].uuid="Compendium.other.componentes-tecnicas.Item.69e4c648b940a68e";assert.throws(()=>componentProfile(item),/Referência/);});
test("adesão é opcional e nenhuma descrição textual antiga é interpretada",()=>{const {system,item}=fixture();item.flags={};item.system.bigbangs="Esgotar; Terreno Favorável";const t=techniqueWithComponents(item);assert.equal(componentState(item).enabled,false);assert.equal(techniqueParameters(system,t).cost,6);assert.throws(()=>techniqueParameters(system,t,{exhaust:1}),/não possui/);assert.equal(item.system.cost,5);});
test("Esgotar cobra dois CE por ND; essência/terreno somam ND; espaço soma alcance sem repetir CE fixa",()=>{const {system,item}=fixture(),t=techniqueWithComponents(item),p=activationPreview(system,t,{exhaust:2,oppositeEssence:true,favorableTerrain:true,componentReason:"Alvo/terreno conferidos"});assert.equal(p.parameters.cost,10);assert.equal(p.parameters.difficulty,20);assert.equal(p.normal.damageLevel,6);assert.equal(p.normal.damage,61);assert.equal(p.critical.damage,71);assert.equal(p.parameters.components.range,7.5);assert.equal(p.payment.fromCurrent,10);assert.equal(item.system.range,3);assert.equal(item.system.damageLevel,2);});
test("opções desligadas não aplicam bônus contextuais; graduações de Espaço mantêm1,5/3/4,5",()=>{const {system,item}=fixture();for(const rank of [1,2,3]){item.flags[ID].techniqueConstructionHistory.saved.components.at(-1).rank=rank;const p=activationPreview(system,techniqueWithComponents(item));assert.equal(p.parameters.cost,6);assert.equal(p.normal.damageLevel,2);assert.equal(p.parameters.components.rangeBonus,rank*1.5);}});
test("tipo, graduação, repetição, mistura primordial e terreno sem parâmetro são recusados",()=>{for(const kind of ["type","rank","duplicate","mixed","terrain"]){const {item}=fixture(),list=item.flags[ID].techniqueConstructionHistory.saved.components;if(kind==="type")list[0].type="increment";if(kind==="rank")list.at(-1).rank=4;if(kind==="duplicate")list.push({...list[0]});if(kind==="mixed")list.push({key:"bigbang:primordial:Controle"});if(kind==="terrain")list[2].detail="";assert.throws(()=>componentProfile(item),undefined,kind);}});
test("opções inválidas ou sem componente são rejeitadas; notas são opcionais",()=>{const {item}=fixture(),t=techniqueWithComponents(item);for(const options of [{exhaust:-1},{exhaust:1.5},{oppositeEssence:"true"},{componentReason:42},{componentReason:"x".repeat(1001)}])assert.throws(()=>componentOptions(t,options));assert.throws(()=>componentOptions({...t,componentProfile:{enabled:true,rules:[]}}, {exhaust:1}),/não possui/);});
test("outros componentes permanecem listados como manuais sem ganho inventado",()=>{const {system,item}=fixture();item.flags[ID].techniqueConstructionHistory.saved.components.push({uuid:`Compendium.${ID}.componentes-tecnicas.Item.e63322f3195be739`,key:"bigbang:extra:Brasas",name:"Brasas",page:"225"});const p=activationPreview(system,techniqueWithComponents(item));assert.equal(p.normal.damage,21);assert.deepEqual(p.parameters.components.manual,[{name:"Brasas",page:"225"}]);});
test("configuração habilita somente composição válida e conserva ND/alcance base",()=>{const {system,item}=fixture(),answer={...item.system,reviewed:true,componentAutomation:true};const updates=techniqueSetupUpdates({system},item,answer);assert.equal(updates[`flags.${ID}.componentAutomation`],true);assert.equal(updates["system.range"],3);assert.equal(updates["system.damageLevel"],2);assert.throws(()=>techniqueSetupUpdates({system},item,{...answer,effectKind:"control"}),/primordial Dano/);item.flags={};assert.throws(()=>techniqueSetupUpdates({system},item,answer),/composição salva/);assert.equal(techniqueSetupUpdates({system},item,{...answer,componentAutomation:false})[`flags.${ID}.componentAutomation`],false);});
test("modo por status usa ND do usuário antes de extras e mantém parâmetros manuais",()=>{const {system,item}=fixture();system.profile.status="gold";item.system.techniqueMode="status";item.system.damageLevel=99;const p=activationPreview(system,techniqueWithComponents(item),{exhaust:2});assert.equal(p.normal.damageLevel,6);assert.equal(p.normal.damage,121);assert.equal(item.system.damageLevel,99);});
test("Essência e Terreno aplicam bônus escolhidos com notas vazias",()=>{
 const {system,item}=fixture();const p=activationPreview(system,techniqueWithComponents(item),{oppositeEssence:true,favorableTerrain:true});assert.equal(p.normal.damageLevel,4);assert.equal(p.parameters.cost,6);assert.equal(p.parameters.difficulty,16);assert.equal(p.payment.fromCurrent,6);
});
